### ISSUE TITLE
Sketch 3.8.1 – Plugin broken

### ISSUE THREAD

**Issue by okbytes** [Falkeyn/Modulizer#7]
When I run either the apply padding or change padding commands, the button bg flips order to on top and the padding doesn't seem to get applied. I can't find a way to make it work 😭

**Comment by aalokt89** [comment]
Same problem for me. In fact, none of the other dynamic button plugins are working for me either

**Comment by billstrahlend** [comment]
This is happening with me as well.

**Comment by Falkeyn** [comment]
Fixed

**Comment by krusemp** [comment]
I still have the same Problem. How do you fixed it? Can you help me?

**Comment by Falkeyn** [comment]
Hi
That's your Sketch version? Have you tried to reinstall the plugin?
